### ISSUE TITLE
"Uncaught TypeError" in peerconnection calls

### ISSUE THREAD

**Issue by cvranjani** [webrtc/apprtc#481] opened 2017-09-11 20:59 UTC
**Browsers and versions affected**
Chrome OS : 62.0.3202.9 / 9901.7.0 dev
Any chrome device

**Steps to reproduce**
1. Browse to https://appr.tc/?debug=loopback and join the loopback call
2. Open the javascript console (alt+cmd+j or ctr+shift+j) and watch for any errors

**Expected results**
Apprtc loopback call should connect successfully and there should not be any javascript errors

**Actual results**
Apprtc loopback call connects successfully but javascript logs shows "Uncaught TypeError: Cannot read property '0' of undefined at PeerConnectionClient.onRemoteStreamAdded_ (apprtc.debug.js:4461)"
[Loopback_js_logs_M62dev.txt](https://github.com/webrtc/apprtc/files/1294012/Loopback_js_logs_M62dev.txt)

![screenshot](https://user-images.githubusercontent.com/15255941/30296033-ab383b00-96f7-11e7-8769-0bb9d6f47edf.png)

Note:
This issue is also observed in apprtc peer2peer calls and other webrtc sample pages for peerconnection calls : https://webrtc.github.io/samples/src/content/peerconnection/pc1/, https://webrtc.github.io/samples/src/content/peerconnection/webaudio-input/

**Comment by cvranjani** [comment] 2017-09-11 21:00
@KaptenJansson

**Comment by KaptenJansson** [comment] 2017-09-12 09:26
I believe this is due to an adapter change, will take a look and see if the web clients need an update or adapter.

FYI @fippo

**Comment by KaptenJansson** [comment] 2017-09-12 12:19
AppRTC is receiving events from both adapter and Chrome, that's why this is happening.

**Comment by fippo** [comment] 2017-09-12 12:54
that does sound familiar... https://bugs.chromium.org/p/chromium/issues/detail?id=761612 ?

**Comment by fippo** [comment] 2017-09-12 13:00
bingo. Only happens without experimental web platform features.

**Comment by henbos** [comment] 2017-09-12 13:03
I will try to fix the Chromium bug.

**Comment by henbos** [comment] 2017-09-12 13:37
Doing pc.addEventListener('track', callback); results in the callback being invoked when ontrack should fire, even though ontrack is behind experimental web platform flags and the flag is off (that's a bug!). Not only does it fire when it shouldn't, because the RTCTrackEvent is behind a flag the event that does fire have undefined track and streams members.

**Comment by henbos** [comment] 2017-09-12 14:06
I have a confirmed fix ready, let's wait for it to land and for it to get into canary.

**Comment by henbos** [comment] 2017-09-13 10:33
I've confirmed this is fixed on tip of tree. Should be in canary shortly if it isn't already.

**Closed by henbos** 2017-09-13 10:33 UTC
