### ISSUE TITLE
Audio ducking in apprtc calls fail in windows

### ISSUE THREAD

**Issue by srnarayanan** [webrtc/apprtc#293] opened 2016-04-26 17:49 UTC
**Browsers and versions affected**
Chrome M49, M50, M51

**Description**
Audio ducking fails in apprtc in Windows

**Steps to reproduce**
(1) Play a local mp3 audio file in Windows
(2) Start a 2 way apprtc call https://appr.tc/?audio=googDucking=true b/w Windows and Linux/Mac

**Expected results**
After the apprtc call is established, the music player stops and user (from Windows) should be able to hear contact (in Linux/Mac) speaking.

**Actual results**
While the user is able to hear the contact speak, the music player (in Win) does not stop/lower volume 

Notes:
This issue is not seen in Hangouts where audio ducking is enabled by default

**Comment by srnarayanan** [comment] 2016-04-26 17:50
CCing @KaptenJansson

**Comment by KaptenJansson** [comment] 2016-04-27 13:46
This is not a bug, audio ducking is not enabled. The question is, should we enable it? @juberti @samdutton

**Comment by KaptenJansson** [comment] 2016-04-27 13:47
Ow I just saw that the constraint is passed in, is that the correct constraint though? Could be that apprtc passes it in as an optional constraint and that's not handled correctly after updating adapter.js. Will look into it.

**Comment by KaptenJansson** [comment] 2018-03-08 11:53
Closing due to age.

**Closed by KaptenJansson** 2018-03-08 11:53 UTC
