### ISSUE TITLE
Don't send a sync XHR in onbeforeunload handler

### ISSUE THREAD

**Issue by mikeconley** [webrtc/apprtc#368] opened 2016-09-14 14:48 UTC
**Browsers and versions affected**
All

**Description**
When the browser tab goes away, the onbeforeunload event causes Call hangups to send a sync XHR.

This appears to be deliberate, and is explicitly called out here: https://github.com/webrtc/apprtc/blob/6a83865f0e74a5d2c1ac197eefc613827835e138/src/web_app/js/call.js#L146

This is pretty bad for performance, especially on slow networks, as the main thread for the content is blocked waiting for the XHR to complete.

It might be possible to do the same work using sendBeacon in supporting browsers: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon

Or perhaps a ServiceWorker would be useful here instead.

**Steps to reproduce**
Open a call on a bad network connection. Close the browser tab.

**Expected results**
There shouldn't be a sync XHR in the onbeforeunload event.

**Actual results**
There's a sync XHR.

**Comment by mikeconley** [comment] 2016-09-14 14:49
This was originally filed as a bug in Mozilla's bug tracker at [https://bugzilla.mozilla.org/show_bug.cgi?id=1250088](https://bugzilla.mozilla.org/show_bug.cgi?id=1250088)

**Comment by KaptenJansson** [comment] 2016-09-15 07:30
Yes its bad for performance but at the same time we need to cleanup in the backend. Interestingly it works fine in Chrome and in earlier Firefox versions hence it's a clear regression in Firefox.

Having said (written) that, we are ofc open to better ways of doing things here. But not sure when.

**Comment by KaptenJansson** [comment] 2018-03-08 11:50
Closing due to age.

**Closed by KaptenJansson** 2018-03-08 11:50 UTC
Labels: enhancement
