### ISSUE TITLE
grunt build (Aborted due to warnings.)

### ISSUE THREAD

**Issue by atonamy** [webrtc/apprtc#247] opened 2015-12-28 10:52 UTC
After I executing grunt build

I getting this

Running "shell:buildAppEnginePackage" (shell) task

Running "shell:genJsEnums" (shell) task
src >>> src/web_app/js

Running "closurecompiler:debug" (closurecompiler) task

Compiling src/web_app/js/analytics.js,src/web_app/js/enums.js,src/web_app/js/adapter.js,src/web_app/js/appcontroller.js,src/web_app/js/call.js,src/web_app/js/constants.js,src/web_app/js/infobox.js,src/web_app/js/peerconnectionclient.js,src/web_app/js/remotewebsocket.js,src/web_app/js/roomselection.js,src/web_app/js/sdputils.js,src/web_app/js/signalingchannel.js,src/web_app/js/stats.js,src/web_app/js/storage.js,src/web_app/js/util.js,src/web_app/js/windowport.js -> out/app_engine/js/apprtc.debug.js
Warning: 1 Use --force to continue.

Aborted due to warnings.

I tried also grunt build --verbose

Initializing
Command-line options: --verbose

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.
Reading package.json...OK
Parsing package.json...OK
Initializing config...OK

Registering "grunt-contrib-csslint" local Npm module tasks.
Reading /home/archie/Projects/apprtc/node_modules/grunt-contrib-csslint/package.json...OK
Parsing /home/archie/Projects/apprtc/node_modules/grunt-contrib-csslint/package.json...OK
Loading "csslint.js" tasks...OK
+ csslint

Registering "grunt-htmlhint" local Npm module tasks.
Reading /home/archie/Projects/apprtc/node_modules/grunt-htmlhint/package.json...OK
Parsing /home/archie/Projects/apprtc/node_modules/grunt-htmlhint/package.json...OK
Loading "htmlhint.js" tasks...OK
+ htmlhint

Registering "grunt-jscs" local Npm module tasks.
Reading /home/archie/Projects/apprtc/node_modules/grunt-jscs/package.json...OK
Parsing /home/archie/Projects/apprtc/node_modules/grunt-jscs/package.json...OK
Loading "jscs.js" tasks...OK
+ jscs

Registering "grunt-contrib-jshint" local Npm module tasks.
Reading /home/archie/Projects/apprtc/node_modules/grunt-contrib-jshint/package.json...OK
Parsing /home/archie/Projects/apprtc/node_modules/grunt-contrib-jshint/package.json...OK
Loading "jshint.js" tasks...OK
+ jshint

Registering "grunt-shell" local Npm module tasks.
Reading /home/archie/Projects/apprtc/node_modules/grunt-shell/package.json...OK
Parsing /home/archie/Projects/apprtc/node_modules/grunt-shell/package.json...OK
Loading "shell.js" tasks...OK
+ shell

Registering "grunt-jstestdriver-phantomjs" local Npm module tasks.
Reading /home/archie/Projects/apprtc/node_modules/grunt-jstestdriver-phantomjs/package.json...OK
Parsing /home/archie/Projects/apprtc/node_modules/grunt-jstestdriver-phantomjs/package.json...OK
Loading "jstdPhantom.js" tasks...OK
+ jstdPhantom

Registering "grunt-closurecompiler" local Npm module tasks.
Reading /home/archie/Projects/apprtc/node_modules/grunt-closurecompiler/package.json...OK
Parsing /home/archie/Projects/apprtc/node_modules/grunt-closurecompiler/package.json...OK
Loading "closurecompiler.js" tasks...OK
+ closurecompiler

Registering "build/grunt-chrome-build" tasks.

Registering "grunt-contrib-compress" local Npm module tasks.
Reading /home/archie/Projects/apprtc/node_modules/grunt-contrib-compress/package.json...OK
Parsing /home/archie/Projects/apprtc/node_modules/grunt-contrib-compress/package.json...OK
Loading "compress.js" tasks...OK
+ compress

Registering "grunt-jinja" local Npm module tasks.
Reading /home/archie/Projects/apprtc/node_modules/grunt-jinja/package.json...OK
Parsing /home/archie/Projects/apprtc/node_modules/grunt-jinja/package.json...OK
Loading "jinja.coffee" tasks...OK
+ jinja
Loading "grunt-chrome-build.js" tasks...OK
+ grunt-chrome-build, grunt-chrome-build-compress, grunt-chrome-build-package, grunt-chrome-build-transform
Loading "Gruntfile.js" tasks...OK
+ build, default, jstests, runPythonTests, travis

Running tasks: build

Running "build" task

Running "shell:buildAppEnginePackage" (shell) task
Verifying property shell.buildAppEnginePackage exists in config...OK
File: [no files]
Options: stdout, stderr, stdin, failOnError, stdinRawMode=false
Command: python ./build/build_app_engine_package.py src out/app_engine

Running "shell:genJsEnums" (shell) task
Verifying property shell.genJsEnums exists in config...OK
File: [no files]
Options: stdout, stderr, stdin, failOnError, stdinRawMode=false
Command: python ./build/gen_js_enums.py src src/web_app/js
src >>> src/web_app/js

Running "closurecompiler:debug" (closurecompiler) task
Verifying property closurecompiler.debug exists in config...OK
Files: src/web_app/js/analytics.js, src/web_app/js/enums.js, src/web_app/js/adapter.js, src/web_app/js/appcontroller.js, src/web_app/js/call.js, src/web_app/js/constants.js, src/web_app/js/infobox.js, src/web_app/js/peerconnectionclient.js, src/web_app/js/remotewebsocket.js, src/web_app/js/roomselection.js, src/web_app/js/sdputils.js, src/web_app/js/signalingchannel.js, src/web_app/js/stats.js, src/web_app/js/storage.js, src/web_app/js/util.js, src/web_app/js/windowport.js -> out/app_engine/js/apprtc.debug.js
Options: compilation_level="WHITESPACE_ONLY", max_processes=1.7976931348623157e+308, language_in="ECMASCRIPT5", formatting="PRETTY_PRINT"

Compiling src/web_app/js/analytics.js,src/web_app/js/enums.js,src/web_app/js/adapter.js,src/web_app/js/appcontroller.js,src/web_app/js/call.js,src/web_app/js/constants.js,src/web_app/js/infobox.js,src/web_app/js/peerconnectionclient.js,src/web_app/js/remotewebsocket.js,src/web_app/js/roomselection.js,src/web_app/js/sdputils.js,src/web_app/js/signalingchannel.js,src/web_app/js/stats.js,src/web_app/js/storage.js,src/web_app/js/util.js,src/web_app/js/windowport.js -> out/app_engine/js/apprtc.debug.js
Warning: 1 Use --force to continue.

Aborted due to warnings.

Any idea whats wrong?

**Comment by atonamy** [comment] 2015-12-28 11:06
Ok fixed. I just did this steps:

npm cache clean
rm -rf node_modules
rm -rf out
npm install grunt@0.4.1
npm install grunt-htmlhint@0.9.9
npm install

and finally

grunt build

And it done, without errors.

**Comment by KaptenJansson** [comment] 2016-01-04 11:41
Hmm that's a bad warning, does not hint about what the issue is.

Did you really need to install those specific versions of grunt and grunt-htmlhint (did you try the same steps but omit the grunt and grunt-htmlhint install steps)?

**Comment by KaptenJansson** [comment] 2016-01-04 13:51
You are most likely hitting https://github.com/webrtc/apprtc/issues/232 which is an external dependency issue. AFAIK there is not much we can do.

**Comment by atonamy** [comment] 2016-01-04 13:56
You can try youself on ubuntu 14.04 LTS 64bit without those specific versions doesn't work.

**Comment by KaptenJansson** [comment] 2016-01-04 16:42
It works for me using my old checkout, I will try on a fresh checkout tomorrow and see if we can get around it somehow.

**Comment by KaptenJansson** [comment] 2016-01-08 14:26
I managed to repro after deleting node_modules.

Could you please try to checkout the #248 PR, delete node_modules and do npm install? It worked for me. If it works I will merge the fix.

**Comment by KaptenJansson** [comment] 2016-01-11 08:48
I've now merged it to the master branch, please try it out.

**Comment by KaptenJansson** [comment] 2016-06-20 13:19
Closing old bugs.

**Closed by KaptenJansson** 2016-06-20 13:19 UTC
