### ISSUE TITLE
InvalidSessionDescriptionError in Firefox Nightly

### ISSUE THREAD

**Issue by bpyoung92** [webrtc/apprtc#432] opened 2017-04-07 20:29 UTC
**Browsers and versions affected**
Firefox Nightly 55.0a1

**Description**
Cannot make any calls using AppRTC.  Run into InvalidSessionDescriptionError.

**Steps to reproduce**
Open debug loopback call in AppRTC in Nightly build.

**Expected results**
Normal loopback call.

**Actual results**
InvalidSessionDescriptionError: Answer contains illegal setup attribute "actpass" at level 0.

**Comment by KaptenJansson** [comment] 2017-04-10 09:52
@jan-ivar any thoughts? I might need to update adapter in AppRTC to the latest but cannot think of a recent change affecting this hence it could be something the firefox nightly that is different?

**Comment by jan-ivar** [comment] 2017-04-11 02:15
@KaptenJansson Unfortunately, I'm not able to test loopback calls in Nightly atm due to [bug 1355306](https://bugzil.la/1355306) (I'm on mac). @bpyoung92 are you getting local self-view camera on both ends? If so, could you pastebin me the sdp offer from the other machine?

I tested it in the march 2nd Nightly (last one before the cams in two tabs broke mac at least), and I was not able to reproduce this sdp problem. I'll ask around.

**Comment by fippo** [comment] 2017-04-11 18:09
53.934: setRemoteDescription: InvalidSessionDescriptionError: Answer has inconsistent direction on extmap attribute at level 0 (urn:ietf:params:rtp-hdrext:ssrc-audio-level). Offer had sendonly, answer had sendrecv.

This looks very much like https://bugzilla.mozilla.org/show_bug.cgi?id=1353028 which was fixed recently.

**Comment by nils-ohlmeier** [comment] 2017-04-11 18:26
The error "InvalidSessionDescriptionError: Answer contains illegal setup attribute "actpass" at level 0." from the original report points to the code added to Firefox in https://bugzilla.mozilla.org/show_bug.cgi?id=1323723.
As Firefox for sure does not use 'actpass' in it's answers something must screw around with the a=setup in the answers. I guess either adapter.js or apprtc.

**Comment by fippo** [comment] 2017-04-11 18:28
```InvalidSessionDescriptionError: Answer contains illegal setup attribute "actpass" at level 0.```
might be due to apprtc doing weird things in loopback mode. @bpyoung92 did you use `?debug=loopback`?

**Comment by nils-ohlmeier** [comment] 2017-04-11 18:34
> 53.934: setRemoteDescription: InvalidSessionDescriptionError: Answer has inconsistent direction on extmap attribute at level 0 (urn:ietf:params:rtp-hdrext:ssrc-audio-level). Offer had sendonly, answer had sendrecv.

I get the same error between Chrome 57 and Fx 55. The reason is that Firefox offers the audio level header extension as sendonly, but replies with no parameter which means it is sendrecv. Since Fx offered only sendonly Chrome is not allowed to change it to sendrecv, but has to either reject the header extension all together or respond with recvonly only.

**Comment by fippo** [comment] 2017-04-11 19:17
filed https://bugs.chromium.org/p/webrtc/issues/detail?id=7477

**Comment by KaptenJansson** [comment] 2018-03-08 10:26
Closing due to age and it works now in Firefox ESR 52.6.0

**Closed by KaptenJansson** 2018-03-08 10:26 UTC
