### ISSUE TITLE
AppRTC Room full after force close

### ISSUE THREAD

**Issue by phoglund** [webrtc/apprtc#397] opened 2016-11-17 12:38 UTC
Filed from https://bugs.chromium.org/p/webrtc/issues/detail?id=6709:

1.Run AppRTCMobile in emulator, call some room
2.Got to https://aapr.tc, connect to room
3.Close AppRTCMobile emulator without hanging up (e.g: right-click + "close window")
3.Close AppRTCMobile emulator without hanging up (e.g: right-click + "close window")
4.Run AppRTCMobile in emulator, call same room as in step 1.

What is the expected result?
Can reconnect to same room

What do you see instead?
"Room Full" error message

What version of the product are you using? On what operating system?
Latest Android AppRTCMobile run in windows emulator.

Please provide any additional information below.
This causes thie issue:
- on first launch AppRTCMobile registers http://appr.tc/join/roomId/clientId
- when crash forcibly ther is no : http://appr.tc/leave/roomId/clientId
- on second launch AppRTCMobile tries to registers: http://appr.tc/join/roomId/newClientId and fails, since the previous client id is still registerd

**Comment by KaptenJansson** [comment] 2016-11-18 07:59
If a client do not send an explicit disconnect message, it will wait for a while before kicking out the client form the room. 

The reason this happens is that we identify the client with a randomly generated ID which is not stored and not reused hence the backend does not know that you are the same client reconnecting.

Reducing the timeout will surely help in some situations but not the quick rejoins since the timeout has to be at least a minute or two I guess.

**Comment by hekra01** [comment] 2016-11-18 10:32
Hi,

I entered the original bug. Reducing the timeout will be good enough (1mn is ok).
Where is it set? I'll try locally

Thanks

**Comment by KaptenJansson** [comment] 2017-05-08 05:59
I thought there was a time out specified somewhere but cannot remember where at the moment, will try to find out.

**Comment by KaptenJansson** [comment] 2018-03-08 11:48
I believe the timeout is here: https://github.com/webrtc/apprtc/blob/master/src/collider/collider/collider.go#L24.

Closing this for now since this is by design for now.

**Closed by KaptenJansson** 2018-03-08 11:48 UTC
Labels: bug

**Comment by CzokNorris** [comment] 2020-01-28 10:33
In my opinion this should not have been closed.

**Comment by nivedn3** [comment] 2020-05-02 04:42
What to do in order to facilitate immediate rejoin after a force close?
